version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Expose Flask server on host
    volumes:
      - ./server:/app
      - /app/server/model_weights.pth

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
        - ./client:/app
    depends_on:
      - server  
    environment:
      SERVER_URL: http://server:5000  # Communicate with server container
